# Generated by Django 3.1.4 on 2020-12-21 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SignRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('envelope_id', models.CharField(max_length=50)),
                ('error_details', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('status_date_time', models.DateTimeField()),
            ],
        ),
    ]
