# Generated by Django 3.1.4 on 2020-12-21 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esign', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signrequest',
            name='error_details',
            field=models.TextField(null=True),
        ),
    ]
