# Generated by Django 3.1.4 on 2020-12-22 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esign', '0002_auto_20201221_1931'),
    ]

    operations = [
        migrations.AddField(
            model_name='signrequest',
            name='attachment',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
