# Generated by Django 3.1.4 on 2021-02-01 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('esign', '0003_signrequest_attachment'),
    ]

    operations = [
        migrations.CreateModel(
            name='SigEnvelope',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('envelope_id', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='signrequest',
            name='envelope_id',
        ),
        migrations.AlterField(
            model_name='signrequest',
            name='status_date_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.CreateModel(
            name='Recipient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('sign_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='esign.signrequest')),
            ],
        ),
        migrations.AddField(
            model_name='signrequest',
            name='envelope',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='esign.sigenvelope'),
        ),
    ]
