# Generated by Django 3.1.4 on 2021-02-01 19:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('esign', '0005_remove_signrequest_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signrequest',
            name='envelope',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='esign.sigenvelope'),
        ),
    ]
